name: Security Scan (SAST & DAST)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ethical-check:
    name: EthicalCheck API Scan
    runs-on: ubuntu-latest
    needs: [zap-scan]  # This ensures the API is running before EthicalCheck starts
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: APIsec Ethical Check
        uses: apisec-inc/apisec-run-scan@v1.0.0
        with:
          apisec-username: ${{ secrets.APISEC_USERNAME }}
          apisec-password: ${{ secrets.APISEC_PASSWORD }}
          apisec-url: "http://localhost:5000"
          apisec-profile: "ethical-check"

  bandit-scan:
    name: Bandit SAST Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run Bandit SAST scan
        run: |
          echo "=== Python Security Scan with Bandit ==="
          bandit -r python_wordstop/ -f txt --exit-zero || true
          echo "========================================"

  trivy-scan:
    name: Trivy SAST Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - uses: actions/checkout@v3

    # SAST Scan with Trivy
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'table'
        output: '/dev/stdout'
        severity: 'CRITICAL,HIGH,MEDIUM'
        exit-code: '0'
    
    # Print Trivy Summary
    - name: Print Trivy Scan Summary
      run: |
        echo "Trivy scan completed. Check the logs above for results."

  zap-scan:
    name: ZAP DAST Scan
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    steps:
    - uses: actions/checkout@v3

    # Setup Python for Flask app
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    # Install Dependencies
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask

    # Build and start applications
    - name: Build and start Python app
      run: |
        cd python_wordstop
        nohup python wordstop.py > flask.log 2>&1 &
        echo "Waiting for Python app to start..."
        # Wait for the app to be ready
        for i in {1..30}; do
          if curl -s http://localhost:5000 > /dev/null; then
            echo "Application is up!"
            break
          fi
          echo "Waiting for application... ($i/30)"
          sleep 2
        done
        # Check if app is really running
        curl -v http://localhost:5000
        if [ $? -ne 0 ]; then
          echo "Application failed to start"
          cat flask.log
          exit 1
        fi

    # Run OWASP ZAP DAST Scan with Full Active and Passive Scanning
    - name: Run ZAP Full Scan
      run: |
        docker pull ghcr.io/zaproxy/zaproxy:stable
        docker run --network=host \
          -v ${PWD}:/zap/wrk/:rw \
          --user root \
          ghcr.io/zaproxy/zaproxy:stable \
          zap-full-scan.py \
          -t http://localhost:5000 \
          -I \
          -j \
          -m 10 \
          -z "-config api.disablekey=true -config scanner.attackOnStart=true -config scanner.threadPerHost=5 -config view.mode=attack -config api.addrs.addr.regex=true -config api.addrs.addr.name=.* -config database.recoverylog=false -addoninstall ascanrulesAlpha -addoninstall ascanrulesBeta"

    # Print ZAP Summary
    - name: Print ZAP Scan Summary
      run: |
        echo "ZAP DAST scan completed. Check the logs above for results."
